#pragma once

// Shared disk-protection protocol for Ring0Core and the desktop client.

#define DISKDRV_PROTOCOL_VERSION 1u

#define IOCTL_DISKDRV_GET_EVENT \
  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x900, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DISKDRV_QUERY_STATE \
  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x901, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DISKDRV_SET_PROTECTION \
  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x902, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DISKDRV_ALLOW_ONCE \
  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x903, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DISKDRV_CLEAR_EVENTS \
  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x904, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DISKDRV_DECIDE_REQUEST \
  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x905, METHOD_BUFFERED, FILE_ANY_ACCESS)

enum DISKDRV_EVENT_TYPE : ULONG {
  DiskDrvEventWriteBlocked = 1,
  DiskDrvEventLayoutBlocked = 2,
};

enum DISKDRV_OPERATION_TYPE : ULONG {
  DiskDrvOperationWrite = 1,
  DiskDrvOperationLayoutIoctl = 2,
};

typedef struct _DISKDRV_EVENT {
  ULONG Version;
  ULONG EventType;
  LARGE_INTEGER TimeStamp;
  ULONG DiskNumber;
  ULONG PartitionStyle;
  ULONG ProcessId;
  ULONG ThreadId;
  ULONGLONG Offset;
  ULONGLONG Length;
  ULONG Flags;
  ULONG Reserved;
  ULONGLONG RequestId;
  WCHAR ProcessImage[260];
  WCHAR Detail[256];
} DISKDRV_EVENT, *PDISKDRV_EVENT;

typedef struct _DISKDRV_STATE_OUTPUT {
  ULONG DiskNumber;
  ULONG PartitionStyle;
  BOOLEAN Enabled;
  BOOLEAN AuditOnly;
  USHORT Reserved;
  ULONGLONG BlockedWriteCount;
  ULONGLONG BlockedLayoutIoctlCount;
  ULONG PendingEventCount;
  ULONG Reserved2;
} DISKDRV_STATE_OUTPUT, *PDISKDRV_STATE_OUTPUT;

typedef struct _DISKDRV_SET_PROTECTION_INPUT {
  ULONG DiskNumber;
  ULONG PartitionStyle;
  BOOLEAN Enabled;
  BOOLEAN AuditOnly;
  USHORT Reserved;
} DISKDRV_SET_PROTECTION_INPUT, *PDISKDRV_SET_PROTECTION_INPUT;

typedef struct _DISKDRV_ALLOW_ONCE_INPUT {
  ULONG DiskNumber;
  ULONG OperationType;
  ULONG ProcessId;
  ULONG TimeoutMs;
  ULONGLONG Offset;
  ULONGLONG Length;
} DISKDRV_ALLOW_ONCE_INPUT, *PDISKDRV_ALLOW_ONCE_INPUT;

typedef struct _DISKDRV_DECIDE_REQUEST_INPUT {
  ULONGLONG RequestId;
  BOOLEAN Allow;
  UCHAR Reserved[7];
} DISKDRV_DECIDE_REQUEST_INPUT, *PDISKDRV_DECIDE_REQUEST_INPUT;
